<%@page pageEncoding="utf-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8/>
        <title>计算BMI</title> 
    </head>
    <body>
	    <h1>Welcome to this system, and this system aims to calculate your bmi. </h1>
	    <h1>This website is generated by Trust, a student in sustc</h1>
	    
	    <h2>Southern University of Science and Technology of China</h2>
		<img src="http://www.sustc.edu.cn/resources/cn/image/p27.png"/>
		
	    <h1>Thanks for using.</h1>
	    <div style = "border:1px solid blue; width:960px; margin:100 auto">
	        <form action="input.do" method="post">
	        	身高(m):<input name="height"/>
	        	体重(kg):<input name="weight"/>
	        	<input type="submit" value="提交"/>
	        </form>
	   </div>
	   <p>
	   </p>
        <div style = "border:1px solid red; width:960px; margin:100 auto">
		<p align="center">
			© 2017 Sustech Trust 西北大学 | 西安交通大学 | 西安工业大学
		</p>
		</div>
    </body>
</html>